Song.create(name: "Water Fountain", artist: "Alec Benjamin", genre: "Hip Hop")
Song.create(name: "Adore You", artist: "Harry Styles", genre: "Hip Hop")
Song.create(name: "The A Team", artist: "Ed Sheeran", genre: "Hip Hop")
Song.create(name: "Intentions", artist: "Justin Bieber", genre: "Hip Hop")
Song.create(name: "Memories", artist: "Maroon 5", genre: "Hip Hop")
Song.create(name: "Happier", artist: "Marshmello & Bastille", genre: "Hip Hop")
Song.create(name: "Easier", artist: "5SOS", genre: "Hip Hop")
Song.create(name: "I Lived", artist: "OneRepublic", genre: "Hip Hop")
Song.create(name: "I'm Yours", artist: "Jason Mraz", genre: "Hip Hop")
Song.create(name: "Radioactive", artist: "Imagine Dragons", genre: "Hip Hop")

Song.create(name: "No Surprise", artist: "Chris Daughtry", genre: "Rock")
Song.create(name: "Boulevard of Broken Dreams", artist: "Green Day", genre: "Rock")
Song.create(name: "Hero", artist: "Skillet", genre: "Rock")
Song.create(name: "Animal I Have Become", artist: "Three Days Grace", genre: "Rock")
Song.create(name: "Gives You Hell", artist: "The All-American Rejects", genre: "Rock")
Song.create(name: "What Are You Waiting For?", artist: "Nickelback", genre: "Rock")
Song.create(name: "Halfway Gone", artist: "Lighthouse", genre: "Rock")
Song.create(name: "New Divide", artist: "Linkin Park", genre: "Rock")
Song.create(name: "Paralyzer", artist: "Finger Eleven", genre: "Rock")
Song.create(name: "Second Chance", artist: "Shinedown", genre: "Rock")

Song.create(name: "Cash Money", artist: "Tyga", genre: "Rap")
Song.create(name: "Freaky Friday", artist: "Lil Dicky feat. Tyga", genre: "Rap")
Song.create(name: "Rap God", artist: "Eminem", genre: "Rap")
Song.create(name: "This is America", artist: "Childish Gambino", genre: "Rap")
Song.create(name: "God's Plan", artist: "Drake", genre: "Rap")
Song.create(name: "New Flame", artist: "Chris Brown feat. Usher & Rick Ross", genre: "Rap")
Song.create(name: "Look Alive", artist: "Rae Sremmurd", genre: "Rap")
Song.create(name: "Time For That", artist: "Kevin Gates", genre: "Rap")
Song.create(name: "Cadillac", artist: "Caskey", genre: "Rap")
Song.create(name: "1Hunnid", artist: "K Camp ft. Fetty Wap", genre: "Rap")

Song.create(name: "Die a Happy Man", artist: "Thomas Rhett", genre: "Country" )
Song.create(name: "H.O.L.Y.", artist: "Florida Georgia Line", genre: "Country" )
Song.create(name: "American Country Love Song", artist: "Jake Owen", genre: "Country" )
Song.create(name: "In Case You Didn't Know", artist: "Brett Young", genre: "Country" )
Song.create(name: "Make it Sweet", artist: "Old Dominion", genre: "Country" )
Song.create(name: "Wagon Wheel", artist: "Darius Rucker", genre: "Country" )
Song.create(name: "Blue Ain't Your Color", artist: "Keith Urban", genre: "Country" )
Song.create(name: "Drunk on Your Love", artist: "Brett Eldredge", genre: "Country" )
Song.create(name: "Chicken Fried", artist: "Zac Brown Band", genre: "Country" )
Song.create(name: "Do I Make You Wanna", artist: "Billy Currington", genre: "Country" )