Song.create(name: "Water Fountain", artist: "Alec Benjamin", genre: "Hip Hop")
Song.create(name: "Adore You", artist: "Harry Styles", genre: "Hip Hop")
Song.create(name: "The A Team", artist: "Ed Sheeran", genre: "Hip Hop")
Song.create(name: "Intentions", artist: "Justin Bieber", genre: "Hip Hop")
Song.create(name: "Memories", artist: "Maroon 5", genre: "Hip Hop")
Song.create(name: "Happier", artist: "Marshmello & Bastille", genre: "Hip Hop")
Song.create(name: "Death of a Bachelor", artist: "Panic! at the Disco", genre: "Hip Hop")


Song.create(name: "No Surprise", artist: "Chris Daughtry", genre: "Rock")
Song.create(name: "Boulevard of Broken Dreams", artist: "Green Day", genre: "Rock")
Song.create(name: "Hero", artist: "Skillet", genre: "Rock")
Song.create(name: "Animal I Have Become", artist: "Three Days Grace", genre: "Rock")
Song.create(name: "Gives You Hell", artist: "The All-American Rejects", genre: "Rock")
Song.create(name: "Paralyzer", artist: "Finger Eleven", genre: "Rock")

Song.create(name: "Cash Money", artist: "Tyga", genre: "Rap")
Song.create(name: "Freaky Friday", artist: "Lil Dicky feat. Tyga", genre: "Rap")
Song.create(name: "Rap God", artist: "Eminem", genre: "Rap")
Song.create(name: "This is America", artist: "Childish Gambino", genre: "Rap")
Song.create(name: "God's Plan", artist: "Drake", genre: "Rap")
Song.create(name: "New Flame", artist: "Chris Brown feat. Usher & Rick Ross", genre: "Rap")

Song.create(name: "Die a Happy Man", artist: "Thomas Rhett", genre: "Country" )
Song.create(name: "H.O.L.Y.", artist: "Florida Georgia Line", genre: "Country" )
Song.create(name: "Heaven", artist: "Kane Brown", genre: "Country" )
Song.create(name: "In Case You Didn't Know", artist: "Brett Young", genre: "Country" )
Song.create(name: "Make it Sweet", artist: "Old Dominion", genre: "Country" )
Song.create(name: "Break Up in a Small Town", artist: "Sam Hunt", genre: "Country" )
Song.create(name: "Blue Ain't Your Color", artist: "Keith Urban", genre: "Country" )
Song.create(name: "Drunk on Your Love", artist: "Brett Eldredge", genre: "Country" )